const ARCHIVE_DB='navi.documentArchive.v1';
const ADMIN_AGENT_ID='92';
const activeArchiveAgent=JSON.parse(localStorage.getItem('navidiaria.activeAgent')||localStorage.getItem('naviturni_logged_agent')||'null');
if(!activeArchiveAgent)location.replace('index.html');
const archiveAdmin=String(activeArchiveAgent?.id)==ADMIN_AGENT_ID;
const archiveUrls=[];
const escapeArchive=value=>String(value||'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function openArchiveDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(ARCHIVE_DB,1);request.onupgradeneeded=()=>request.result.createObjectStore('documents',{keyPath:'id'});request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function archiveDocuments(){const db=await openArchiveDb();return new Promise((resolve,reject)=>{const request=db.transaction('documents').objectStore('documents').getAll();request.onsuccess=()=>resolve(request.result.sort((a,b)=>a.createdAt-b.createdAt));request.onerror=()=>reject(request.error)})}
async function saveArchiveDocument(document){const db=await openArchiveDb();return new Promise((resolve,reject)=>{const request=db.transaction('documents','readwrite').objectStore('documents').put(document);request.onsuccess=resolve;request.onerror=()=>reject(request.error)})}
async function deleteArchiveDocument(id){const db=await openArchiveDb();return new Promise((resolve,reject)=>{const request=db.transaction('documents','readwrite').objectStore('documents').delete(id);request.onsuccess=resolve;request.onerror=()=>reject(request.error)})}
function documentCard(document){const url=URL.createObjectURL(document.file);archiveUrls.push(url);const type=document.type==='bozza'?'BOZZA · NON DEFINITIVA':document.type==='ods'?'ODS':'TURNO',icon=document.type==='ods'?'ODS':'PDF',draft=document.type==='bozza'?' draft-document':'';return `<article class="document local-document${draft}" data-open-document="${url}" role="link" tabindex="0" aria-label="Apri ${escapeArchive(document.title)}"><span class="${document.type==='ods'?'ods-number':'pdf-icon'}">${icon}</span><div><small>${type} · CARICATO</small><strong>${escapeArchive(document.title)}</strong><p>${new Intl.DateTimeFormat('it-IT',{dateStyle:'medium'}).format(new Date(document.createdAt))}</p></div><b>↗</b>${archiveAdmin?`<button class="document-delete" type="button" data-delete-document="${escapeArchive(document.id)}">Elimina</button>`:''}</article>`}
async function renderArchiveDocuments(){archiveUrls.splice(0).forEach(URL.revokeObjectURL);const documents=await archiveDocuments(),turni=documents.filter(document=>document.type!=='ods'),ods=documents.filter(document=>document.type==='ods').sort((a,b)=>b.createdAt-a.createdAt);document.getElementById('uploadedTurni').innerHTML=turni.map(documentCard).join('');document.getElementById('uploadedOds').innerHTML=ods.map(documentCard).join('');const counts=document.querySelectorAll('.section-heading .count');if(counts[0])counts[0].textContent=`${2+turni.length} documenti`;if(counts[1])counts[1].textContent=`${10+ods.length} documenti`}
document.addEventListener('DOMContentLoaded',()=>{const staticOds=document.getElementById('staticOds');[...staticOds.children].reverse().forEach(card=>staticOds.appendChild(card));document.getElementById('adminUploadPanel').hidden=!archiveAdmin;document.getElementById('archiveAdminNav').hidden=!archiveAdmin;document.getElementById('archiveSidebarAgent').textContent=String(activeArchiveAgent?.name||'Agente').trim().toLocaleUpperCase('it');renderArchiveDocuments().catch(console.error)});
document.getElementById('archiveLogout').addEventListener('click',()=>{localStorage.removeItem('navidiaria.activeAgent');localStorage.removeItem('naviturni_logged_agent');location.href='index.html'});
document.getElementById('archiveChangePin').addEventListener('click',()=>{location.href='navidiaria.html?pin=1'});
document.getElementById('documentUploadForm').addEventListener('submit',async event=>{event.preventDefault();if(!archiveAdmin)return;const file=document.getElementById('documentFile').files[0],message=document.getElementById('uploadMessage');if(!file||(!file.name.toLowerCase().endsWith('.pdf')&&file.type!=='application/pdf')){message.textContent='Seleziona un file PDF valido.';return}if(file.size>25*1024*1024){message.textContent='Il PDF non può superare 25 MB.';return}const type=document.getElementById('documentType').value,title=file.name.trim().replace(/\s+/g,'_');await saveArchiveDocument({id:crypto.randomUUID(),type,title,file,createdAt:Date.now(),uploadedBy:String(activeArchiveAgent.id)});event.target.reset();message.textContent=`${title} caricato nell’archivio locale.`;await renderArchiveDocuments()});
document.addEventListener('click',async event=>{const button=event.target.closest('[data-delete-document]');if(button){event.stopPropagation();if(!archiveAdmin||!confirm('Eliminare questo documento dall’archivio?'))return;await deleteArchiveDocument(button.dataset.deleteDocument);await renderArchiveDocuments();return}const card=event.target.closest('[data-open-document]');if(card)window.open(card.dataset.openDocument,'_blank','noopener')});
document.addEventListener('keydown',event=>{const card=event.target.closest('[data-open-document]');if(card&&(event.key==='Enter'||event.key===' ')){event.preventDefault();window.open(card.dataset.openDocument,'_blank','noopener')}});
window.addEventListener('beforeunload',()=>archiveUrls.forEach(URL.revokeObjectURL));
