const DIARIA_SESSION='navidiaria.activeAgent',TURNI_SESSION='naviturni_logged_agent';
const $=id=>document.getElementById(id);
function hasSecureCrypto(){return typeof window!=='undefined'&&!!(window.crypto&&window.crypto.subtle&&typeof window.crypto.subtle.digest==='function')}
function isLocalDevHost(){const host=String(location.hostname||'').toLowerCase();return host==='localhost'||host==='127.0.0.1'||host==='::1'||/^(10\.|192\.168\.|172\.(1[6-9]|2\d|3[0-1])\.)/.test(host)}
function useDevPinFallback(){return !hasSecureCrypto()&&typeof window!=='undefined'&&window.isSecureContext===false&&isLocalDevHost()}
function weakHashPin(pin){let hash=2166136261,text=`NaviDiaria:${pin}`;for(let i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash+=(hash<<1)+(hash<<4)+(hash<<7)+(hash<<8)+(hash<<24)}return`dev-${(hash>>>0).toString(16).padStart(8,'0')}`}
async function hashPin(pin){if(hasSecureCrypto()){const bytes=new TextEncoder().encode(`NaviDiaria:${pin}`);const hash=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(hash)].map(value=>value.toString(16).padStart(2,'0')).join('')}if(useDevPinFallback()){console.warn('TODO: rimuovere fallback PIN non crittografico prima della produzione.');return weakHashPin(pin)}throw new Error('Questa pagina richiede HTTPS (Web Crypto non disponibile).')}
let agent=null;try{agent=JSON.parse(localStorage.getItem(DIARIA_SESSION)||localStorage.getItem(TURNI_SESSION)||'null')}catch(_){}
if(!agent)location.replace('index.html');else $('changePinTitle').textContent=`Modifica il PIN di ${agent.name||agent.agente||agent.cognome||'utente'}`;
$('cancelPinButton').addEventListener('click',()=>{if(history.length>1)history.back();else location.replace('index.html')});
$('changePinForm').addEventListener('submit',async event=>{event.preventDefault();const current=$('currentPin').value,next=$('newPin').value,confirmation=$('confirmPin').value,message=$('changePinMessage'),button=$('changePinSubmit'),localKey=`navidiaria.pin.${agent.id}`;if(next!==confirmation){message.textContent='I nuovi PIN non coincidono.';return}button.disabled=true;message.textContent='Salvataggio online…';try{const pinHash=await hashPin(current),newPinHash=await hashPin(next);if(useDevPinFallback()){ // TODO: rimuovere fallback cambio PIN locale prima della produzione.
if(localStorage.getItem(localKey)&&pinHash!==localStorage.getItem(localKey)){message.textContent='Il PIN attuale non è corretto.';return}localStorage.setItem(localKey,newPinHash);message.style.color='#087e71';message.textContent='PIN aggiornato in fallback sviluppo (solo locale).';setTimeout(()=>location.replace('index.html'),650);return}
await NaviCloud.request('change_pin',{agentId:agent.id,pinHash,newPinHash});localStorage.setItem(localKey,newPinHash);message.style.color='#087e71';message.textContent='PIN modificato correttamente.';setTimeout(()=>location.replace('index.html'),650)}catch(error){message.textContent=error.message||'Impossibile modificare il PIN.'}finally{button.disabled=false}});
