(()=>{
  const daysNode=document.getElementById('weeklyDays');
  if(!daysNode)return;
  const rangeNode=document.getElementById('weeklyRange'),totalsNode=document.getElementById('weeklyTotals');
  const dayFmt=new Intl.DateTimeFormat('it-IT',{weekday:'short'}),rangeFmt=new Intl.DateTimeFormat('it-IT',{day:'numeric',month:'short'}),longFmt=new Intl.DateTimeFormat('it-IT',{weekday:'long',day:'numeric',month:'long'});
  let weekStart=monday(new Date());
  const groundServices=new Set(['AGB','POND','DT','PT','AGM','AGT','PONM','LD']);
  function monday(value){const d=new Date(value);d.setHours(12,0,0,0);const day=d.getDay()||7;d.setDate(d.getDate()-day+1);return d}
  function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
  function addDays(d,n){const next=new Date(d);next.setDate(next.getDate()+n);return next}
  function entryFor(date){return entries.find(entry=>entry.date===date)}
  function worked(entry){return entry?Math.round(shiftFor(entry.shift).hours*60)+(Number(entry.delay)||0):0}
  function card(entry,date){const dateIso=iso(date),today=dateIso===todayIso(),future=dateIso>todayIso(),sunday=date.getDay()===0,shift=entry?.shift||'—',competence=entry?shiftFor(shift):null,base=entry?Math.round(competence.hours*60):0,delay=Number(entry?.delay)||0,bank=(Number(entry?.bank)||0)+refuelCredit(entry||{})+travelCredit(entry||{}),meal=competence?.meal?(entry.mealUsed?'BP usato':'BP da accreditare'):'Nessun BP',allowance=entry?.allowanceRate;
    return `<article class="weekly-day${today?' is-today':''}${future?' is-future':''}${sunday?' is-sunday':''}" data-date="${dateIso}"><div class="weekly-day-head"><span class="weekly-day-name">${dayFmt.format(date)}</span><span class="weekly-day-number">${date.getDate()}</span></div><div class="weekly-shift">${escapeHtml(String(shift))}</div><div class="weekly-hours">${entry?(groundServices.has(String(shift).toUpperCase())?'Servizio a terra':`Durata ${minutesToText(base)} · presenza a bordo anticipata`):'Turno non disponibile'}</div>${entry?`<div class="weekly-metrics"><span class="weekly-chip">${minutesToText(worked(entry))}</span>${delay?`<span class="weekly-chip is-overtime">+${delay} min</span>`:''}${bank?`<span class="weekly-chip is-bank">Banca ${minutesToText(bank)}</span>`:''}<span class="weekly-chip is-meal">${meal}</span>${allowance!==null&&allowance!==undefined?`<span class="weekly-chip is-allowance">Diaria ${allowance}%</span>`:''}</div><button class="day-card-edit" type="button" data-edit-day="${entry.id}">Modifica giornata</button>`:'<p class="weekly-empty">Aggiorna i turni oppure aggiungi la giornata.</p>'}</article>`}
  function renderWeeklyCalendar(){const dates=Array.from({length:7},(_,i)=>addDays(weekStart,i)),weekEntries=dates.map(d=>entryFor(iso(d))).filter(Boolean),workedTotal=weekEntries.reduce((n,e)=>n+worked(e),0),manualExtra=weekEntries.reduce((n,e)=>n+(Number(e.delay)||0),0),overtime=Math.max(0,workedTotal-manualExtra-39*60)+manualExtra,bank=weekEntries.reduce((n,e)=>n+(Number(e.bank)||0)+refuelCredit(e)+travelCredit(e),0),meals=weekEntries.filter(e=>shiftFor(e.shift).meal),used=meals.filter(e=>e.mealUsed).length,allowances={};weekEntries.forEach(e=>{if(e.allowanceRate!==null&&e.allowanceRate!==undefined)allowances[e.allowanceRate]=(allowances[e.allowanceRate]||0)+1});rangeNode.textContent=`${rangeFmt.format(dates[0])} – ${rangeFmt.format(dates[6])}`;daysNode.innerHTML=dates.map(d=>card(entryFor(iso(d)),d)).join('');totalsNode.innerHTML=[['Ore',minutesToText(workedTotal)],['Straordinari',minutesToText(overtime)],['Banca ore',minutesToText(bank)],['Buoni pasto',`${used} usati · ${Math.max(0,meals.length-used)} credito`],['Diaria',Object.entries(allowances).map(([r,n])=>`${n}×${r}%`).join(' · ')||'—']].map(([l,v])=>`<div class="weekly-total"><small>${l}</small><strong>${v}</strong></div>`).join('');requestAnimationFrame(()=>daysNode.querySelector('.is-today')?.scrollIntoView({inline:'center',block:'nearest'}))}
  daysNode.addEventListener('click',event=>{const button=event.target.closest('[data-edit-day]');if(button){startEdit(button.dataset.editDay);return}const day=event.target.closest('[data-date]');if(!day||entryFor(day.dataset.date))return;resetEntryForm();document.getElementById('entryDate').value=day.dataset.date;document.getElementById('dayEditorTitle').textContent=`Aggiungi ${longFmt.format(new Date(day.dataset.date+'T12:00:00'))}`;document.getElementById('dayEditor').hidden=false;document.getElementById('entryForm').hidden=false;document.getElementById('entryForm').style.display='grid';document.getElementById('dayEditor').scrollIntoView({behavior:'smooth',block:'start'})});
  document.getElementById('weeklyPrevious').addEventListener('click',()=>{weekStart=addDays(weekStart,-7);renderWeeklyCalendar()});document.getElementById('weeklyNext').addEventListener('click',()=>{weekStart=addDays(weekStart,7);renderWeeklyCalendar()});document.getElementById('weeklyToday').addEventListener('click',()=>{weekStart=monday(new Date());renderWeeklyCalendar()});document.addEventListener('navidiaria:render',renderWeeklyCalendar);renderWeeklyCalendar();
})();
