(()=>{
  const sheet=document.getElementById('monthlySheet'),weekly=document.getElementById('weeklyCalendar'),grid=document.getElementById('monthlySheetGrid'),title=document.getElementById('monthlySheetTitle');if(!sheet||!grid)return;
  const monthFmt=new Intl.DateTimeFormat('it-IT',{month:'long',year:'numeric'}),weekFmt=new Intl.DateTimeFormat('it-IT',{weekday:'short'}),fixedHolidays=new Set(['01-01','01-06','04-25','05-01','06-02','08-15','11-01','12-08','12-25','12-26']);
  const rows=[
    {key:'service',label:'Servizio',unit:'',value:e=>isWorking(e)?e.shift:''},
    {key:'service-hours',label:'Ore servizio',unit:'H',value:e=>isWorking(e)?clock(Math.round(shiftFor(e.shift).hours*60)):''},
    {key:'overtime',label:'Lavoro straordinario',unit:'MIN',value:e=>isWorking(e)?minutes(e?.delay):''},
    {key:'bank',label:'Banca ore',unit:'MIN',value:e=>isWorking(e)?minutes((Number(e?.bank)||0)+refuelCredit(e||{})+travelCredit(e||{})):''},
    {key:'hours',label:'Ore lavorate',unit:'H',value:e=>isWorking(e)?clock(Math.round(shiftFor(e.shift).hours*60)+(Number(e.delay)||0)):''},
    {key:'hydrofoil',label:'Ind. aliscafo',unit:'',value:e=>check(isWorking(e)&&e?.hydrofoil)},
    {key:'allowance9',label:'Diarie 9%',unit:'',allowance:true,value:e=>check(isWorking(e)&&Number(e?.allowanceRate)===9)},
    {key:'allowance24',label:'Diarie 24%',unit:'',allowance:true,value:e=>check(isWorking(e)&&Number(e?.allowanceRate)===24)},
    {key:'allowance40',label:'Pernott. 40% nav.',unit:'',allowance:true,value:e=>check(isWorking(e)&&Number(e?.allowanceRate)>24&&!e?.travel)},
    {key:'travel',label:'Trasferta 50%',unit:'',allowance:true,value:e=>check(isWorking(e)&&e?.travel)},
    {key:'holiday',label:'Festività',unit:'',value:(e,d)=>check(isWorking(e)&&isHoliday(d))},
    {key:'missed-rest',label:'Mancato riposo',unit:'',value:e=>check(isWorking(e)&&e?.missedRest)},
    {key:'ticket',label:'Ticket presenza',unit:'',value:e=>check(isWorking(e))},
    {key:'canteen',label:'Mensa',unit:'',value:e=>check(isWorking(e)&&e.mealUsed)},
    {key:'second-ticket',label:'2° ticket presenza',unit:'',value:e=>check(isWorking(e)&&e?.secondMeal)},
    {key:'embark',label:'Ind. imbarco',unit:'',value:e=>check(isWorking(e)&&e.embark)}
  ];
  const shiftColors={D1:'#2563eb',D2:'#059669',D3:'#ea580c',D4:'#c026d3',BIS:'#0891b2',POND:'#dc2626',DT:'#d4a900',AGB:'#2563eb',LD:'#64748b',PT:'#64748b',AGM:'#64748b',AGT:'#64748b',PONM:'#dc2626'};
  function isWorking(e){return !!e&&!['RIPOSO','RIP','MALATTIA'].includes(String(e.shift||'').toUpperCase())}
  function check(v){return v?'✓':''}function minutes(v){const n=Math.round(Number(v)||0);return n?`${n}`:''}function clock(v){const m=Math.max(0,Math.round(Number(v)||0));return `${Math.floor(m/60)}:${String(m%60).padStart(2,'0')}`}function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}function isHoliday(d){return d.getDay()===0||fixedHolidays.has(iso(d).slice(5))}function monthDate(){const [y,m]=document.getElementById('monthFilter').value.split('-').map(Number);return new Date(y,m-1,1,12)}
  function dayPresentation(e){if(!isWorking(e))return {className:'',style:''};const color=shiftColors[String(e.shift).toUpperCase()]||'#64748b';return {className:'shift-column ',style:` style="--day-color:${color}"`}}
  function renderMonthly(){const first=monthDate(),count=new Date(first.getFullYear(),first.getMonth()+1,0).getDate(),dates=Array.from({length:count},(_,i)=>new Date(first.getFullYear(),first.getMonth(),i+1,12)),today=todayIso();title.textContent=monthFmt.format(first).replace(/^./,c=>c.toUpperCase());const head=`<thead><tr><th class="monthly-label">Voci</th>${dates.map(d=>{const e=entries.find(x=>x.date===iso(d)),p=dayPresentation(e);return `<th${p.style} class="${p.className}${d.getDay()===0||d.getDay()===6?'weekend ':''}${isHoliday(d)?'holiday ':''}${iso(d)===today?'today-column':''}">${weekFmt.format(d).slice(0,2)}<br><strong>${String(d.getDate()).padStart(2,'0')}</strong></th>`}).join('')}</tr></thead>`;const body=rows.map(row=>`<tr class="row-${row.key}${row.allowance?' row-allowance':''}"><th class="monthly-label">${row.label}<span class="monthly-unit">${row.unit}</span></th>${dates.map(d=>{const e=entries.find(x=>x.date===iso(d)),p=dayPresentation(e);return `<td${p.style} data-date="${iso(d)}" class="${p.className}${d.getDay()===0||d.getDay()===6?'weekend ':''}${isHoliday(d)?'holiday ':''}${iso(d)===today?'today-column':''}">${escapeHtml(String(row.value(e,d)||''))}</td>`}).join('')}</tr>`).join('');grid.innerHTML=`<table class="monthly-table">${head}<tbody>${body}</tbody></table>`;requestAnimationFrame(()=>grid.querySelector('.today-column')?.scrollIntoView({inline:'center',block:'nearest'}))}
  function openDate(date){const entry=entries.find(e=>e.date===date);if(entry){startEdit(entry.id);return}resetEntryForm();document.getElementById('entryDate').value=date;document.getElementById('dayEditorTitle').textContent=`Aggiungi ${date}`;document.getElementById('dayEditor').hidden=false;document.getElementById('entryForm').hidden=false;document.getElementById('entryForm').style.display='grid';document.getElementById('dayEditor').scrollIntoView({behavior:'smooth',block:'start'})}
  grid.addEventListener('click',e=>{const cell=e.target.closest('[data-date]');if(cell)openDate(cell.dataset.date)});function moveMonth(delta){const d=monthDate();d.setMonth(d.getMonth()+delta);document.getElementById('monthFilter').value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;render();renderMonthly()}
  document.getElementById('monthlyPrevious').addEventListener('click',()=>moveMonth(-1));document.getElementById('monthlyNext').addEventListener('click',()=>moveMonth(1));document.getElementById('monthlyToday').addEventListener('click',()=>{document.getElementById('monthFilter').value=todayIso().slice(0,7);render();renderMonthly()});
  const monthlyButton=document.getElementById('showMonthlySheet'),weeklyButton=document.getElementById('showWeeklyCalendar');function setView(mode){const monthly=mode==='monthly';sheet.hidden=!monthly;weekly.hidden=monthly;monthlyButton.classList.toggle('active',monthly);weeklyButton.classList.toggle('active',!monthly);localStorage.setItem('navidiaria.view',mode);if(monthly)renderMonthly()}
  monthlyButton.addEventListener('click',()=>setView('monthly'));weeklyButton.addEventListener('click',()=>setView('weekly'));document.addEventListener('navidiaria:render',renderMonthly);setView(localStorage.getItem('navidiaria.view')||'monthly');
})();
