(()=>{
  const sheet=document.getElementById('monthlySheet'),weekly=document.getElementById('weeklyCalendar'),grid=document.getElementById('monthlySheetGrid'),title=document.getElementById('monthlySheetTitle');if(!sheet||!grid)return;
  const monthFmt=new Intl.DateTimeFormat('it-IT',{month:'long',year:'numeric'}),weekFmt=new Intl.DateTimeFormat('it-IT',{weekday:'short'}),fixedHolidays=new Set(['01-01','01-06','04-25','05-01','06-02','08-15','11-01','12-08','12-25','12-26']);
  const rows=[
    {key:'service',label:'Servizio',unit:'',value:e=>e?.shift||''},
    {key:'hours',label:'Ore lavorate',unit:'H',value:e=>e?clock(Math.round(shiftFor(e.shift).hours*60)+(Number(e.delay)||0)):''},
    {key:'overtime',label:'Lavoro straordinario',unit:'H',value:e=>e?.delay?clock(e.delay):''},
    {key:'hydrofoil',label:'Ind. aliscafo',unit:'N',value:e=>number(e?.hydrofoil)},
    {key:'allowance9',label:'Diarie 9%',unit:'N',allowance:true,value:e=>Number(e?.allowanceRate)===9?'1':''},
    {key:'allowance24',label:'Diarie 24%',unit:'N',allowance:true,value:e=>Number(e?.allowanceRate)===24?'1':''},
    {key:'allowance40',label:'Pernott. 40% nav.',unit:'N',allowance:true,value:e=>Number(e?.allowanceRate)>24?`${e.allowanceRate}%`:''},
    {key:'holiday',label:'Festività',unit:'H',value:(e,d)=>e&&isHoliday(d)?clock(Math.round(shiftFor(e.shift).hours*60)):''},
    {key:'missed-rest',label:'Mancato riposo',unit:'H',value:e=>e?.missedRest?clock(e.missedRest):''},
    {key:'ticket',label:'Ticket presenza',unit:'N',value:e=>e&&shiftFor(e.shift).meal?'1':''},
    {key:'canteen',label:'Mensa',unit:'N',value:e=>e?.mealUsed?'1':''},
    {key:'second-ticket',label:'2° ticket presenza',unit:'N',value:e=>number(e?.secondMeal)},
    {key:'embark',label:'Ind. imbarco',unit:'N',value:e=>e?.embark?'1':''}
  ];
  function number(v){return Number(v)>0?String(v):''}function clock(v){const m=Math.max(0,Math.round(Number(v)||0));return `${Math.floor(m/60)}:${String(m%60).padStart(2,'0')}`}function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}function isHoliday(d){return d.getDay()===0||fixedHolidays.has(iso(d).slice(5))}function monthDate(){const [y,m]=document.getElementById('monthFilter').value.split('-').map(Number);return new Date(y,m-1,1,12)}
  function renderMonthly(){const first=monthDate(),count=new Date(first.getFullYear(),first.getMonth()+1,0).getDate(),dates=Array.from({length:count},(_,i)=>new Date(first.getFullYear(),first.getMonth(),i+1,12)),today=todayIso();title.textContent=monthFmt.format(first).replace(/^./,c=>c.toUpperCase());const head=`<thead><tr><th class="monthly-label">Voci</th>${dates.map(d=>`<th class="${d.getDay()===0||d.getDay()===6?'weekend ':''}${isHoliday(d)?'holiday ':''}${iso(d)===today?'today-column':''}">${weekFmt.format(d).slice(0,2)}<br><strong>${String(d.getDate()).padStart(2,'0')}</strong></th>`).join('')}</tr></thead>`;const body=rows.map(row=>`<tr class="row-${row.key}${row.allowance?' row-allowance':''}"><th class="monthly-label">${row.label}<span class="monthly-unit">${row.unit}</span></th>${dates.map(d=>{const e=entries.find(x=>x.date===iso(d));return `<td data-date="${iso(d)}" class="${d.getDay()===0||d.getDay()===6?'weekend ':''}${isHoliday(d)?'holiday ':''}${iso(d)===today?'today-column':''}">${escapeHtml(String(row.value(e,d)||''))}</td>`}).join('')}</tr>`).join('');grid.innerHTML=`<table class="monthly-table">${head}<tbody>${body}</tbody></table>`;requestAnimationFrame(()=>grid.querySelector('.today-column')?.scrollIntoView({inline:'center',block:'nearest'}))}
  function openDate(date){const entry=entries.find(e=>e.date===date);if(entry){startEdit(entry.id);return}resetEntryForm();document.getElementById('entryDate').value=date;document.getElementById('dayEditorTitle').textContent=`Aggiungi ${date}`;document.getElementById('dayEditor').hidden=false;document.getElementById('entryForm').hidden=false;document.getElementById('entryForm').style.display='grid';document.getElementById('dayEditor').scrollIntoView({behavior:'smooth',block:'start'})}
  grid.addEventListener('click',e=>{const cell=e.target.closest('[data-date]');if(cell)openDate(cell.dataset.date)});function moveMonth(delta){const d=monthDate();d.setMonth(d.getMonth()+delta);document.getElementById('monthFilter').value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;render();renderMonthly()}
  document.getElementById('monthlyPrevious').addEventListener('click',()=>moveMonth(-1));document.getElementById('monthlyNext').addEventListener('click',()=>moveMonth(1));document.getElementById('monthlyToday').addEventListener('click',()=>{document.getElementById('monthFilter').value=todayIso().slice(0,7);render();renderMonthly()});
  const monthlyButton=document.getElementById('showMonthlySheet'),weeklyButton=document.getElementById('showWeeklyCalendar');function setView(mode){const monthly=mode==='monthly';sheet.hidden=!monthly;weekly.hidden=monthly;monthlyButton.classList.toggle('active',monthly);weeklyButton.classList.toggle('active',!monthly);localStorage.setItem('navidiaria.view',mode);if(monthly)renderMonthly()}
  monthlyButton.addEventListener('click',()=>setView('monthly'));weeklyButton.addEventListener('click',()=>setView('weekly'));document.addEventListener('navidiaria:render',renderMonthly);setView(localStorage.getItem('navidiaria.view')||'monthly');
})();
